version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data