import './globals.css'
import type { Metadata } from 'next';
import { inter } from '@/config/fonts'
import { Provider } from '@/components';

export const metadata: Metadata = {
  title: 'AutoRepuestos Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>  
    </html>
  )
}
